// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2sTyF8SaFNxWk8FlCAlzht1l3aqegpzk',
    appId: '1:299064197006:web:cb5e568d0f48b74ffd6edf',
    messagingSenderId: '299064197006',
    projectId: 'flutter-internship-onix',
    authDomain: 'flutter-internship-onix.firebaseapp.com',
    storageBucket: 'flutter-internship-onix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGMWLdvhfZFYO1dcC6rBZ6ueWDg8z0Tbk',
    appId: '1:299064197006:android:07bd427e1a055967fd6edf',
    messagingSenderId: '299064197006',
    projectId: 'flutter-internship-onix',
    storageBucket: 'flutter-internship-onix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5XpUPUPA3WcseewAq8sGgMugwqckXY50',
    appId: '1:299064197006:ios:69028424f6dfaa40fd6edf',
    messagingSenderId: '299064197006',
    projectId: 'flutter-internship-onix',
    storageBucket: 'flutter-internship-onix.appspot.com',
    iosClientId: '299064197006-b5mr648slt9fsde6gh0c8fq3so6ijpil.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );
}
